### PR TITLE
Update zhTW/zhCN

### PR DESCRIPTION
**Pull request by EKE00372**
as #10 said, some of locales need more talk, I only translate options at this time and it's ok without merge, just take out translate locales.

and some suggest, we can use UI_ERROR_MESSAGE without locales, and need global strings when custom chat text.

UI_ERROR_MESSAGE:
SPELL_FAILED_NOT_SHAPESHIFT
SPELL_FAILED_NO_ITEMS_WHILE_SHAPESHIFTED
SPELL_NOT_SHAPESHIFTED
SPELL_NOT_SHAPESHIFTED_NOSPACE
ERR_CANT_INTERACT_SHAPESHIFTED
ERR_NOT_WHILE_SHAPESHIFTED
ERR_NO_ITEMS_WHILE_SHAPESHIFTED
ERR_TAXIPLAYERSHAPESHIFTED
ERR_MOUNT_SHAPESHIFTED
ERR_EMBLEMERROR_NOTABARDGEOSET
SPELL_FAILED_NOT_STANDING 
SPELL_FAILED_NOT_MOUNTED
ERR_ATTACK_MOUNTED

and global string such like this: (it's a custom style for myself)
https://github.com/EKE00372/EKChat/blob/master/GlobalStrings.lua
GlobalStrings are here, possible use this although PTR version because most of them are same.
https://www.townlong-yak.com/framexml/ptr/GlobalStrings.lua

### CODE REVIEW

**Comment by obble** [comment]
Thanks for this! Will review in the next day or so

**Comment by obble** [comment]
russian translation also kindly provided by GJSmoker on wowinterface to introduce to locale.lua file:

https://gist.github.com/obble/fe7700e670e5b142395bec0b57fca206

**Comment by EKE00372** [comment]
so......is there anything i can/i need to do now?

**Comment by obble** [comment]
I just need to get off my bum and implement your work :o)

**Pull request merged**
